### ISSUE TITLE
Exception caught by SVG: tried to call a non-function, such as null: 'this.function._equals'

### ISSUE THREAD

**Issue by phaylali** [dnfield/flutter_svg#536]
```
════════ Exception caught by SVG ═══════════════════════════════════════════════
The following JSNoSuchMethodError was thrown resolving a single-frame picture stream:
NoSuchMethodError: tried to call a non-function, such as null: 'this.function._equals'

packages/petitparser/src/definition/reference.dart 19:11                          _equals
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 687:60  equals
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 147:17         _get
packages/petitparser/src/definition/grammar.dart 138:27                           _dereference
packages/petitparser/src/definition/grammar.dart 163:30                           [_resolve]
...
Picture provider: ExactAssetPicture(name: "res/icons/plus.svg", bundle: null, colorFilter: null)
Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#526cb(), name: "res/icons/plus.svg", colorFilter: null)

════════ Exception caught by SVG ═══════════════════════════════════════════════
NoSuchMethodError: tried to call a non-function, such as null: 'this.function._equals'
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by SVG ═══════════════════════════════════════════════
NoSuchMethodError: tried to call a non-function, such as null: 'this.function._equals'
════════════════════════════════════════════════════════════════════════════════
```

everything was working just a 2 days ago , after i updated flutter and pubspec.yaml , all svgs' in my app are not working they show nothing,

**Comment by dnfield** [comment]
Can you share an SVG and pubspec that recreates this? Or perhaps an entire project?

It'd be helpful to note which version of Flutter as well (which commit).

**Comment by phaylali** [comment]
https://github.com/phaylali/albourane/tree/master/admin

I SHOULD NOTE THAT THE PROBLEM HAPPENS ON FLUTTER WEB, LATEST DEV CHANNEL 

if it didn't work just make a firebase-config.js in the web folder and put some dummy project credentials there

**Comment by phaylali** [comment]
i tried it on flutter stable , and it's working fine on the web, i'm closing this issue for now , but there might be some issue in the future releases that may break all packages depending on svg

**Comment by doppio** [comment]
I don't think this issue should be closed, I am seeing the same issue on the Flutter beta channel.

**Comment by doppio** [comment]
@dnfield
https://github.com/doppio/svg_error_example Here is a very simple example project that just displays a simple icon SVG.

An error is printed to the console when you run it on web on the latest Flutter beta (v2.2.0-10.1.pre, commit 0941968). The project works as expected on the stable channel (v2.0.5, commit adc6878)

**Comment by phaylali** [comment]
> @dnfield
> https://github.com/doppio/svg_error_example Here is a very simple example project that just displays a simple icon SVG.
> 
> When you run it web using the latest Flutter beta (v2.2.0-10.1.pre, commit 0941968), you'll see that no image is displayed and the exception reported by @phaylali is printed to the console. The project works as expected on the stable channel (v2.0.5, commit adc6878) as well as the _previous_ beta release (v2.1.0-12.2.pre, commit 5bedb7b).

Yeah, that's why the developer must investigate what's causing that, because if what causing that got merged in the stable channel, the package and all packages depending on it will break (yes i tried other packages that depend on this one and they didn't work) having it work on stable, is more of a temporary workaround rather than a solution,

**Comment by doppio** [comment]
In that case, would you mind re-opening the issue @phaylali?

**Comment by dnfield** [comment]
I'm able to reproduce this easily with the example SVG app in this repo.

This seems like abug in DDC.

**Comment by dnfield** [comment]
This is a bug in ddc.

Minimal repro:

```
void main() {
  Function f1 = () { print('f1'); };
  Function f2 = () { print('f2'); };

  print(f1 == f2);
}
```

You'll find it works in profile or release mode, but not debug mode, because of DDC.

**Comment by dnfield** [comment]
Filed https://github.com/dart-lang/sdk/issues/45762, closing this issue in favor of that one.

**Comment by lukepighetti** [comment]
@dnfield I poked around the issues and they all appear to claim that the issue above was resolved by a cherry picked commit on beta... but we're getting this issue on `dev`

```
Flutter 2.2.0-10.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 0941968447 (11 days ago) • 2021-04-15 12:01:02 -0700
Engine • revision d2a2e93510
Tools • Dart 2.13.0 (build 2.13.0-211.6.beta)
```

```
════════ Exception caught by SVG ═══════════════════════════════════════════════
NoSuchMethodError: tried to call a non-function, such as null: 'this.function._equals'
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by SVG ═══════════════════════════════════════════════
NoSuchMethodError: tried to call a non-function, such as null: 'this.function._equals'
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by SVG ═══════════════════════════════════════════════
NoSuchMethodError: tried to call a non-function, such as null: 'this.function._equals'
```

**Comment by lukepighetti** [comment]
@dnfield I'm trying to get visibility on where this fix is in relation to the `dev` flutter/flutter channel. I haven't been able to find a way to really understand where the cherry pick is. Our team is currently unable to run the app on web in dev mode because of this issue so I'm trying to find some relief.

**Comment by dnfield** [comment]
see https://github.com/dart-lang/sdk/issues/45762#issuecomment-827822209

**Comment by dnfield** [comment]
Flutter's latest beta channel has the fix for this.

**Comment by Azzeccagarbugli** [comment]
> Flutter's latest beta channel has the fix for this.

On the master channel I still have the issue, so that's pretty strange

**Comment by Azzeccagarbugli** [comment]
> Are you sure you're up to date with the latest revision?

Pretty sure! 

<details>
<summary>Flutter doctor output</summary>
<br>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.3.0-1.0.pre.181, on macOS 11.3 20E232 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
```
</details>

**Comment by lukepighetti** [comment]
This is resolved on `dev` channel FWIW
